jwt:
  secret: 'Testing_ABC_BGE_272727'

server:
  port: 5000

spring:
  datasource:
    url: jdbc:mysql://cmr.ciygt781rl3w.us-east-2.rds.amazonaws.com:3306/customerportal
    password: test1234
    username: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5Dialect
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
#  mvc:
#    throw-exception-if-no-handler-found: true
#  resources:
#    add-mappings: false
logging:
  level.com.java.customerportal: debug
