jwt:
  secret: 'Testing_ABC_BGE_272727'

server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/customerportal
    password: letmein
    username: letmein
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
#  mvc:
#    throw-exception-if-no-handler-found: true
#  resources:
#    add-mappings: false
logging:
  level.com.java.customerportal: trace

